name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.15.1
    with:
      image: ghcr.io/radiorabe/grafana
      name: grafana
      display-name: RaBe Grafana on UBI9
      tags: minimal rhel9 ubi9 rabe grafana
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.15.1
